### ISSUE TITLE
Implementar un algoritmo para identificar preguntas similares a una pregunta dada

### ISSUE THREAD

**Issue by anna-ayn** [USB-CI3715/nodebb-usb-24-stars#28]
Desarrollar un algoritmo que permita identificar preguntas similares a un texto dado por el usuario. El objetivo de esto es mejorar la experiencia del usuario al facilitar el acceso a información relacionada.

Dependencias: Ninguna.
Hitos: Sprint 2

Criterios de Aceptación:
1. El algoritmo debe ser capaz de identificar al menos un conjunto de preguntas similares a la pregunta o texto dado.
2. Debe tener alguna relación las preguntas sugeridas con la pregunta dada (por ejemplo, cantidad de palabras similares)
3. Realizar pruebas que demuestren la efectividad del algoritmo en diferentes escenarios y con diferentes tipos de preguntas.

**Esfuerzo alto:** La creación del algoritmo implica el uso de técnicas avanzadas para encontrar similitudes entre las preguntas. Se necesitarán pruebas extensivas para validar la efectividad del algoritmo en diversos escenarios, lo cual puede incluir la creación de conjuntos de datos para evaluar su rendimiento y precisión. También es probable que se requieran múltiples iteraciones para ajustar el algoritmo y mejorar su precisión, lo que aumentará el tiempo y esfuerzo necesarios.

**Comment by ChuyB** [comment]
Creo que este algoritmo sería de esfuerzo alto (o muy alto)
