### ISSUE TITLE
Buscador de preguntas por etiqueta

### ISSUE THREAD

**Issue by anna-ayn** [USB-CI3715/nodebb-usb-24-stars#31]
Permitir a los usuarios buscar preguntas dada una etiqueta y visualizarlas en una lista.

Dependencias: Ninguna
Hitos: Sprint 2

Criterios de Aceptación:
1. Poder buscar todas las preguntas relacionadas a la etiqueta.
1. Poder visualizar esa lista de preguntas.
2. El usuario puede acceder fácilmente a cualquier pregunta que se encuentra en esta lista dándole clic.

**Esfuerzo bajo:** La tarea implica realizar una consulta en la base de datos para recuperar las preguntas asociadas a la etiqueta seleccionada y mostrarlas en la interfaz de usuario.

**Comment by JenniferGamez** [comment]
Se cierra este issue, debido a que NodeBB ya posee esta funcionalidad.
