### ISSUE TITLE
Implementar lógica de filtrado para mostrar las preguntas del usuario actual

### ISSUE THREAD

**Issue by oliebueno** [USB-CI3715/nodebb-usb-24-stars#51]
Modificar la interfaz de visualización de preguntas para que se actualice dinámicamente con las preguntas hechas por el usuario actual

Dependencias: #50 
Hitos: Sprint 2

Criterios de aceptación:

1. La consulta debe devolver solo las preguntas del usuario actual.

**Esfuerzo bajo:** Esta tarea implica realizar la consulta  en la base de datos y mostrar en la interfaz el resultado, por lo que se estima que el tiempo de trabajo sea de 1 hora a 2 horas.

**Comment by JenniferGamez** [comment]
Este issue se realizó al crear el botón del issue #50 .
