### ISSUE TITLE
Implementar notificaciones de respuestas nuevas

### ISSUE THREAD

**Issue by oliebueno** [USB-CI3715/nodebb-usb-24-stars#56]
Implementar la lógica para enviar notificaciones cuando hay nuevas respuestas en las preguntas marcadas como favoritas.

Dependencias: #55 
Hitos: Sprint 2

Criterios de Aceptación: 

1. Los usuarios deben recibir notificaciones cuando haya nuevas respuestas en sus preguntas favoritas.
2. Las notificaciones deben tener un mensaje claro y conciso.
3. El usuario debe poder acceder fácilmente a la pregunta que tiene respuestas nuevas y que están marcadas como favoritas.

**Esfuerzo medio**: Desarrollar el código necesario para enviar las notificaciones al usuario junto con el mensaje puede requerir 5-6 horas.

**Comment by JenniferGamez** [comment]
Se cierra este issue, NodeBB ya posee este mecanismo de notificaciones.
