### ISSUE TITLE
Paginación de Items

### ISSUE THREAD

**Issue by anna-ayn** [USB-CI3715/nodebb-usb-24-stars#59]
Implementar un sistema de paginación que permita a los usuarios navegar fácilmente entre las preguntas o respuestas.

Dependencias: Ninguna
Hitos: Sprint 1

Criterios de Aceptación:
1. Los usuarios deben poder avanzar y retroceder entre las páginas de preguntas o respuestas sin problemas, con controles visibles (ej. "Siguiente", "Anterior", número de página).

**Comment by JenniferGamez** [comment]
Este ticket ha sido implementado en el momento de la creación de la sección de preguntas y respuestas.
