### ISSUE TITLE
Filtrar preguntas por curso

### ISSUE THREAD

**Issue by anna-ayn** [USB-CI3715/nodebb-usb-24-stars#60]
Implementar la lógica para filtrar preguntas por etiqueta del curso.

Dependencias: Issue #50 
Hitos: Sprint 1

Criterios de Aceptación:
1. El usuario debe poder introducir el nombre del curso en el buscador.
2. Al darle al botón de filtrado, se visualiza la lista de las preguntas existentes relacionadas a ese curso.

**Esfuerzo medio:** Implementar el sistema de filtrado por curso implica crear consultas a la base de datos para obtener las preguntas relacionadas con la etiqueta del curso y luego visualizarlas en la interfaz.

**Comment by JenniferGamez** [comment]
Se transfirió el issue #60 debido a que la implementación requería atención de alguien con mayor experiencia. Esto se debe a que el esfuerzo necesario para llevar a cabo la implementación es considerado medio, y se trata de una tarea que no está implementada en el sistema de NodeBB.

**Comment by oliebueno** [comment]
Se implementó un botón que permita a los usuarios filtrar las preguntas por la etiqueta del curso

Hitos
Sprint 1: Esta tarea se incluye en el primer sprint del proyecto.

Issue: #60

- Se añadió un botón en la barra de topicos de la nueva sección, al ser presionado, muestra un input para agregar la etiqueta.
- Al hacer clic en el botón, se realizar una solicitud a la base de datos para extraer las etiquetas que a suvez son desplegadas.
- Las etiquetas desplegadaz también son botones.
- Al presionar algún boton de las etiquetas, este trae las preguntas de la base de datos.
- Aunque se traen las preguntas de la base de datos, aún no se logra renderizar correctamente. Eso se deja para el sprint 2.
