### ISSUE TITLE
Implementar notificaciones de respuestas nuevas en las preguntas hechas por el usuario

### ISSUE THREAD

**Issue by anna-ayn** [USB-CI3715/nodebb-usb-24-stars#63]
Implementar la lógica para enviar notificaciones a un usuario determinado cuando hay nuevas respuestas en las preguntas hechas por este usuario.

Dependencias: Issue #27 
Hitos: Sprint 2

Criterios de Aceptación:
1. Los usuarios deben recibir notificaciones cuando hay nuevas respuestas en sus preguntas hechas.
2. Las notificaciones deben tener un mensaje claro y conciso. 
3. El usuario debe poder acceder fácilmente a la pregunta que tiene respuestas nuevas.

**Esfuerzo medio**: Desarrollar el código necesario para enviar las notificaciones al usuario junto con el mensaje puede requerir 5-6 horas.

**Comment by JenniferGamez** [comment]
Se issue se cierra debido a que NodeBB ya posee esta implementación.
