### ISSUE TITLE
Actualizar interfaz para mostrar solo preguntas marcadas como favoritas por el usuario actual

### ISSUE THREAD

**Issue by anna-ayn** [USB-CI3715/nodebb-usb-24-stars#69]
Modificar la interfaz de visualización de preguntas para que se visualice las preguntas marcadas como favoritas por el usuario actual.

Dependencias: Issue #53 #58 
Hitos: Sprint 1

Criterios de Aceptación:

La interfaz debe mostrar solo las preguntas del usuario actual cuando se hace clic en el botón filtrado.

**Comment by oliebueno** [comment]
Se añadio un botón a la interfaz para que al hacer click, el usuario pueda filtrar las preguntas marcadas como favoritas.

- Las preguntas se filtran y renderizan correctamente
