### ISSUE TITLE
Adaptar la eliminación de una pregunta sin respuestas

### ISSUE THREAD

**Issue by ChuyB** [USB-CI3715/nodebb-usb-24-stars#71]
Un usuario debe poder eliminar una pregunta que no haya tenido ninguna respuesta aún. Esto con el objetivo de permitir eliminar un posible error o una pregunta no deseada. En caso de que la pregunta ya haya tenido alguna respuesta, no debería poderse eliminar.

Dependencias: ninguno.
Hitos: sprint 2.

Criterios de aceptación:
1. Verificar que la pregunta a eliminar no tenga respuestas.
2. El usuario que creó la pregunta debe poder eliminarla

**Esfuerzo bajo:** NodBB ya implementa la eliminación de publicaciones. Debe agregarse la consideración de que esta pregunta no haya tenido respuesta.

**Comment by JenniferGamez** [comment]
Se cierra este issue, ya está implementado en NodeBB.
