### ISSUE TITLE
Actualizar el formulario de registro

### ISSUE THREAD

**Issue by oliebueno** [USB-CI3715/nodebb-usb-24-stars#73]
Añadir campos para nombres y apellidos en el formulario de registro.

Dependencias:
Hitos: Sprint 2

Criterios de Aceptación: 

1. Los campos "Nombre" y "Apellido" deben aparecer en el formulario de registro y ser obligatorios.

**Esfuerzo bajo**: Agregar ambos campos toma menos de 1 hora para implementarlo.

**Comment by JenniferGamez** [comment]
Se cierra este issue, ya está implementado en NodeBB.
