### ISSUE TITLE
Actualizar el modelo de datos del usuario

### ISSUE THREAD

**Issue by oliebueno** [USB-CI3715/nodebb-usb-24-stars#76]
Modificar el modelo de datos del usuario para incluir los campos de nombres y apellidos.

Dependencias: #73 
Hitos: Sprint 2

Criterios de Aceptación: 

1. Los nombres y apellidos deben ser guardados en la base de datos cuando un nuevo usuario se registre.

**Esfuerzo bajo:** Modificar el modelo de la base de datos para que guarde esta información puede tomar entre 1-2 horas o menos.

**Comment by JenniferGamez** [comment]
Se cierra este issue, ya está implementado en NodeBB.
