### ISSUE TITLE
Mostrar nombres y apellidos en el perfil de usuario

### ISSUE THREAD

**Issue by oliebueno** [USB-CI3715/nodebb-usb-24-stars#77]
Modificar la interfaz de usuario para mostrar los nombres y apellidos en el perfil del usuario.

Dependencias: #76
Hitos: Sprint 2

Criterios de Aceptación: 

1. Los nombres y apellidos deben ser visibles en el perfil del usuario para todos los usuarios del sistema.

**Esfuerzo bajo:** Esta tarea puede tomar menos de 1 hora.

**Comment by JenniferGamez** [comment]
Se cierra este issue, ya está implementado en NodeBB.
